language:
- node_js
node_js:
- 14
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm test
after_success:
- bash .travis.deploy.sh
before_deploy:
- ls -al
- cd dist
deploy:
  provider: npm
  email: mat@mlefree.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
